# -*- coding: utf-8 -*-
"""p1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nu6Nc7Wpsu5gFnyYLssfGI3q41xRj2sU
"""

A = {
    0: [1, 2, 3],
    1: [0, 2, 4, 5],
    2: [0, 1, 6],
    3: [0],
    4: [1],
    5: [1],
    6: [2]
}
from collections import deque

def bfs(A):
    answer = []
    # TODO : BFS로 탐색하는 로직을 구현해주세요。
    # 방문한 노드를 순서대로 answer 리스트에 넣어서 리턴해주세요。

    """
    너비우선 탐색: 그래프의 모든 노드를 방문
    deque를 queue로 사용한다.
    시작노드인 0번부터 가까운 노드부터 방문하는데 이때
    같은 레벨인 경우는 번호가 작은 노드부터 방문하도록 실행한다.
    queue는 처음에 들어온 것이 처음으로 나가기 때문에 먼저 들어온 노드를 먼저 꺼낸다
    """

    locQueue = deque([0])
    visited = {0}

    while locQueue:
      node = locQueue.popleft()
      answer.append(node)

      for n in sorted(A[node]):
        if n not in visited:
          visited.add(n)
          locQueue.append(n)
    return answer


def dfs(A):
    answer = []
    # TODO : DFS로 탐색하는 로직을 구현해주세요。
    # 방문한 노드를 순서대로 answer 리스트에 넣어서 리턴해주세요。


    """
    깊이 우선 탐색: 그래프의 모든 노드를 방문
    deque를 stack으로 사용한다.
    시작노드인 0번부터 한 방향으로 끝까지 가다가 더 이상 길이 없을 때에는
    가장 가까운 길로 돌아와서 다른 방향으로 탐색한다.
    stack은 처음으로 들어온게 마지막에 나가기 때문에 스택 제일 위쪽에는
    번호가 작은 노드가 있게 되기에 pop 실행할 때 작은 번호부터 visited로 표시한다
    같은 레벨인 경우는 번호가 작은 노드부터 방문하도록 실행한다.
    방문한 노드는 visited로 표시해 중복되지 않게 한다.
    """

    locDeque = deque([0])
    visited = {0}

    while locDeque:
      node = locDeque.pop()
      answer.append(node)

      for n  in sorted(A[node], reverse=True):
        if n not in visited:
          visited.add(n)
          locDeque.append(n)

    return answer

# 아래는 체크함수입니다. 수정하실 필요 없습니다。
bfs_result = bfs(A)
dfs_result = dfs(A)

assert bfs_result == [0,1,2,3,4,5,6]
assert dfs_result == [0,1,4,5,2,6,3]
print('PASSED!')