# -*- coding: utf-8 -*-
"""p2.py : 2번 코딩 문제

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PyvQwpq9a49XqDyzAIl3mbjVdh5F80uy
"""

import sys
from collections import deque
## 입력 받는 코드입니다. 수정할 필요 없습니다.
sys.stdin = open('case.txt')
N, M = list(map(int,input().split()))
print(N, M)
concerts = []
for v in range(N):
    values = list(map(int, input().split()))
    concerts.append(values)
# print(concerts)
# [[1, 0, 0, 1, 1, 0], [1, 0, 1, 1, 0, 0], [1, 1, 1, 1, 0, 1], [0, 1, 1, 0, 1, 1], [0, 1, 0, 0, 1, 0]]
###################################
def isValidloc(r,c):

  """
  행과 열이 탐색할 수 있는 수 인지 확인한다
  탐색 할 수 없는 수(행과 열보다 수가 크거나 음수) 이면 false로 반환한다
  """
  if r<0 or c<0 or r>=N or c>=M:
    return False
  return concerts[r][c] ==0
def count_stages(concerts):


    """
    콘서트장에서 무대의 개수를 반환한다
    0이 써있는 공간은 하나의 무대이다
    방문한 노드는 -1로 표시한 후 다시 방문하지 않도록 한다
    deque를 사용해 append와 pop을 사용해서 bfs 방법으로 작성한다.
    1이 써있는 공간은 펜스를 나타낸 것이다.
    """
    answer = 0
    # TODO : 콘서트 공간에서 무대의 개수를 계산해 반환해주는 함수를 작성해주세요.
    for i in range(N):
        for j in range(M):
            if concerts[i][j] ==0:
                locQueue=deque()
                locQueue.append((i,j))
                concerts[i][j]= -1

                while locQueue:
                    r,c = locQueue.popleft()

                    if isValidloc(r-1,c):
                        concerts[r-1][c]=-1
                        locQueue.append((r-1,c))

                    if isValidloc(r+1,c):
                        concerts[r+1][c]=-1
                        locQueue.append((r+1,c))

                    if isValidloc(r,c-1):
                        concerts[r][c-1]=-1
                        locQueue.append((r,c-1))

                    if isValidloc(r,c+1):
                        concerts[r][c+1]=-1
                        locQueue.append((r,c+1))

                answer +=1


    return answer

print(count_stages(concerts))